### ISSUE TITLE
switch没有反应

### ISSUE THREAD

**Issue by liqiang1304** [LASER-Yi/homebridge-mi-acpartner#11]
为啥switch开关设置了， 而且出现了， 但是开关没有反应。
switchMulti开关倒是有反应， 但是报错 [XiaoMiAcPartner] [SWITCHMULTI_ERROR]Send fail! Error

**Comment by LASER-Yi** [comment]
学习功能还有点问题 我对比了一下学习到的码，大部分是和从空调伴侣中直接拿到的码不一样的，貌似小米在学习以后进行了处理，这个目前也是无能为力的

**Comment by liqiang1304** [comment]
感谢! 要是有红外就方便了
