### ISSUE TITLE
Customize IR Signal

### ISSUE THREAD

**Issue by cjinsider** [LASER-Yi/homebridge-mi-acpartner#12]
hello! 
In the section of adding IR commands instruction and an example of a configuration file, the values FE018254234ON and FE019205313OFF are indicated. Where can they be found?

**Comment by LASER-Yi** [comment]
you can get it the same method as customize AC signal. Or you can use learnIR button. But there's some bug in that button so I don't recommand you use it.

**Comment by cjinsider** [comment]
Ок. How can I get methods as customize AC signal?
