### ISSUE TITLE
请问下温度传感器怎么才能作为 homekit 的自动化条件

### ISSUE THREAD

**Issue by BaranWang** [LASER-Yi/homebridge-mi-acpartner#14]
现在加入温度传感器后看自动化中感应器这块还是灰色的，是目前的版本还没有做吗？

**Comment by LASER-Yi** [comment]
貌似温度传感器无法在HK中作为自动化条件，需要这个功能可以安装home assistant

**Comment by phenix13** [comment]
可以通过eve等第三方homekit软件创建自动化来实现
