### ISSUE TITLE
未抓取到空调码

### ISSUE THREAD

**Issue by Raccooon** [LASER-Yi/homebridge-mi-acpartner#25]
安装好抓包工具和miio后
开始进行抓包

使用米家app遥控空调
空调响应

返回抓包软件查看
只有简单的握手操作，并没有抓到响应的空调码
我哪个步骤做错了？

**Comment by LASER-Yi** [comment]
米家app和空调需要在同一个设备下，比如你使用电脑抓包，那么需要电脑跑一个安卓模拟器来遥控空调

**Comment by Raccooon** [comment]
谢谢，教程我阅读的不够仔细

**Comment by foretony5211** [comment]
推荐一个安卓模拟器呗。

**Comment by Raccooon** [comment]
网易mumu，简单用一下就好了

发自我的 iPhone

**Comment by foretony5211** [comment]
非常感谢🙏

**Comment by foretony5211** [comment]
@Raccooon 感谢🙏
