### ISSUE TITLE
自定义空调码不工作

### ISSUE THREAD

**Issue by aaronjang** [LASER-Yi/homebridge-mi-acpartner#27]
填入自定义空调码,用-D运行查看发现任何命令发出去码都是OFF状态的码.
                    "name": "客厅空调",
                    "type": "climate",
                    "syncInterval": 3000,
                    "sensorSid": "lumi.158d000208fb7e",
                    "deviceIp": "192.168.0.117",
                    "maxTemp": "30",
                    "minTemp": "17",
                    "customize": {
                        "off": "01000093770130190100C340E000A000200000000005A8",
                        "on": "",
                        "auto": "01000093771230191100C388E000A000000000200000EB",
                        "heat":{
                            "30": "",
                            "29": "",
                            "17": ""
                        },
                        "cool":{
                            "30": "010000937710001E1100C3B0E000A00000000020000013",
                            "29": "010000937711301D1100C3A8E000A0000000002000000B",
                            "28": "010000937711301C1100C3A0E000A00000000020000003",
                            "27": "010000937711301B1100C398E000A000000000200000FB",
                            "26": "010000937711301A1100C390E000A000000000200000F3",
                            "25": "01000093771130191100C388E000A000000000200000EB",
                            "24": "01000093771130181100C380E000A000000000200000E3",
                            "23": "01000093771130171100C378E000A000000000200000DB",
                            "22": "01000093771130161100C370E000A000000000200000D3",
                            "21": "01000093771130151100C368E000A000000000200000CB",
                            "20": "01000093771130141100C360E000A000000000200000C3",
                            "19": "01000093771130131100C358E000A000000000200000BB",
                            "18": "01000093771130121100C350E000A000200000200000D3",
                            "17": "01000093771130111100C348E000A000000000200001AC"
                        }
                    }

**Comment by LASER-Yi** [comment]
修复了这个问题，请更新到0.6.4试试
