### ISSUE TITLE
日立RA-08MF不能匹配第一代空调伴侣

### ISSUE THREAD

**Issue by tonylsl** [LASER-Yi/homebridge-mi-acpartner#30]
家中日立RA-08MF(本身是沒有搖控)未能匹配第一代空调伴侣，手機app有抓到空调伴侣，但沒有辦法匹配，請求指教怎樣自行匹配該冷氣？
謝謝！

**Comment by LASER-Yi** [comment]
手机App里面选择日立，然后一个一个匹配预设试试

**Comment by tonylsl** [comment]
有…12個我都試過…都不行

**Comment by tonylsl** [comment]
希望達人可以教教我可以怎樣修改

**Comment by LASER-Yi** [comment]
如果没有遥控器，就不太好匹配了，因为空调伴侣的码库中也没有这个空调的编码。建议咨询一下小米的官方客服
