### ISSUE TITLE
有关 heaterCooler 属性问题

### ISSUE THREAD

**Issue by junyilou** [LASER-Yi/homebridge-mi-acpartner#34]
之前配置了 climate 发现没有风速，还比较需要于是改成了 heaterCooler，然后用 Siri 想控制温度发现是 “找不到有关设备”，当然 Home app 是可以调整的于是猜测 heaterCooler 并不是注册的空调这种类型，不知道实际上是什么，有没有办法在 heaterCooler 下 Siri 控制温度？
改成 climate 发现果然可以用 Siri 调温度了，很不错的插件，作者辛苦

**Comment by LASER-Yi** [comment]
Climate在Home中注册的类型是“恒温器“，Siri可以识别成空调。HeaterCooler注册的类型是“加热/冷却设备”大部分在Homekit中的空调注册的还是恒温器，因此Siri无法识别这个也无能为力

**Comment by junyilou** [comment]
那如果说是加热冷却设备的话有没有指令可以做到让 Siri 控制呢？不过这个其实也不是问题了，iOS 12 的 Shortcut 出来之后这些都可以自定义了用我特定的话来操作都可以
