### ISSUE TITLE
控制Mi AC partner2 電源開關

### ISSUE THREAD

**Issue by newsam3** [LASER-Yi/homebridge-mi-acpartner#37]
Is the ac partner2 possible to work like a smart power outlet that work same as the zigbee power outlet?
小米空调伴侣2 可以像zigbee電源插座一樣只控制電源開關嗎？

**Comment by tkmark** [comment]
这个插件不行，home-assistant里的插件（xiaomi_aqara）也不行，其他的就不知道了，二代空调伴侣发布不久，有些新组合特性还得等待现有插件更新才能使用。

**Comment by newsam3** [comment]
谢谢回复, 这插件对于没有遥控器的旧空调，完全用不了!!!!

**Comment by LASER-Yi** [comment]
@newsam3 麻烦看一下Wiki的抓包教程，然后在米家中控制电源开闭，把他们之间的通讯发给我。
因为我手头上没有第二代空调伴侣，不好加这个功能，只好麻烦一下你了。

**Comment by newsam3** [comment]
谢谢大大幫忙, 抓包seems quite complicate, 讓我用點時間研究一下...

**Comment by newsam3** [comment]
LASER-Yi 抓包ed, 因為我不知道如何在這裡放那些代碼，所以我已經下載了它，你可以從下面的鏈接下載

https://1drv.ms/u/s!AoIGW6dEjvqLjwYZmTPkGZe94UjY

谢谢大大幫忙

**Comment by LASER-Yi** [comment]
非常感谢协助，请提供一下你空调伴侣的token

**Comment by newsam3** [comment]
token: 229dfa6f232632dfbc01dbbfe1c305fb
ip: 192.168.11.149

**Comment by LASER-Yi** [comment]
拿到操作了，十分感谢协助。预计下个版本更新这个功能

**Comment by newsam3** [comment]
Thanks so much Laser-Yi

**Comment by LASER-Yi** [comment]
已经更新，请安装最新的版本

**Comment by newsam3** [comment]
Thanks so much Laser-Yi, it really helps me.
btw, do you have schedule to add the  function of reading 断路器状态?

**Comment by LASER-Yi** [comment]
In fact I don't know how to read it. Can you catch the protocol between mijia app and acpartner of reading breaker state?

**Comment by newsam3** [comment]
I totally have no idea how to get that protocol, is it also use the wireshark?

**Comment by LASER-Yi** [comment]
Yes. Just start wireshark record and open acpartner page in mijia app. Control your breaker several times and send what you got in wireshark to me.

**Comment by newsam3** [comment]
Thanks for your intrusion. It running for few days, it really works flawlessly.
But I am just a newbie for coding, can you comment my writing below?

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
              },
    "platforms":
 [
          {
           "platform": "MiAqaraPlatform",
           "gateways": {"7811dcb3a10e": "1E246904178b4FC2"}
          },
         {
            "platform": "XiaoMiAcPartner",
            "devices":{
                "192.168.11.149":"229dfa6f232632dfbc01dbbfe1c305fb"
                      },
            "accessories":[
                           {
                            "name": "AC Partner",
                            "type": "heaterCooler",
                            "breaker": true
                           }
                          ]
          }
 ]
}

Below is the recording file from Wireshark.
https://1drv.ms/u/s!AoIGW6dEjvqLjwpONYyrfI0iKpZ3

**Comment by newsam3** [comment]
I want to receive the status info from the ACpartner badly, is the 0.7.2 u listed a beta? if so, do you have schedule for download the non-beta V. 0.7.2?
