### ISSUE TITLE
日立预设1不生效，附上错误代码

### ISSUE THREAD

**Issue by saury** [LASER-Yi/homebridge-mi-acpartner#39]
设备是lumi.acpartner.v3.，空调日立预设1。以下为错误信息：
```
[2018-7-12 22:17:14] [XiaoMiAcPartner] [DEBUG]Sending AC code: 010001123210001b00
[2018-7-12 22:17:14] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"acpartner.v3","sid":"7811dcb2a10c","params":[{"ac_state":268442369},{"ac_power":1},{"illumination":35}]}
[2018-7-12 22:17:14] [XiaoMiAcPartner] [Ac Partner]Send code failed! Error: (null)
```
看readme中说可适配大多数预设1，鉴于v3太奇葩了，miio和类似mi-aqara-homebridge都有问题，附上错误信息求证是否需要自己抓包，另外问下mac下用什么模拟器比较好，试过genymotion，老是闪退，万分无奈。

**Comment by Raccooon** [comment]
需要抓包，我感觉sync功能基本形同虚设，也可能我没有设置对。
你需要抓包关闭信号，（很多空调给他一个温度就开启了）
30-17的所有信号
贴一下我的美的空调的，仅供参考
  "accessories": [
                {
                    "name": "Ac Partner",
                    "type": "climate",
                    "customize": {
                        "off": "010001127201311a01004DB2DE2107F8",
                        "on": "",
                        "auto": "",
                        "heat": {
                            "30": "",
                            "29": "",
                            "17": ""
                        },
                        "cool": {
"30": "010001127211311e11004DB2FD020DF2",
"29": "010001127211311d11004DB2FD0205FA",
"28": "010001127211311c11004DB2FD0201FE",
"27": "010001127211311b11004DB2FD0209F6",
"26": "010001127211311a11004DB2FD020BF4",
"25": "010001127211311911004DB2FD0203FC",
"24": "010001127211311811004DB2FD0202FD",
"23": "010001127211311711004DB2FD020AF5",
"22": "010001127211311611004DB2FD020EF1",
"21": "010001127211311511004DB2FD0206F9",
"20": "010001127211311411004DB2FD0204FB",
"19": "010001127211311311004DB2FD020CF3",
"18": "010001127211311211004DB2FD0208F7",
"17": "010001127211311111004DB2FD0200FF2"
