### ISSUE TITLE
Door/Window sensors

### ISSUE THREAD

**Issue by Dengor1984** [LASER-Yi/homebridge-mi-acpartner#4]
Hello! 
Thanks for a great plugin!!!
Now I can use Cooper&Hunter air conditioner with preset Gree No1 with homekit and Siri.

Can you, please, add in plugin support of door/window sensors, if it possible?

**Comment by LASER-Yi** [comment]
If your door/window sensors is connected with AC Partner, it's very hard to support because Xiaomi didn't make LAN protocol for AC Partner. You can connect your door/window sensors to Xiaomi Gateway and this [plugin](https://github.com/YinHangCode/homebridge-mi-aqara) can support it.

**Comment by Dengor1984** [comment]
I have automation in AC Partner with window sensor and I can’t connect it to Gateway v2.
I have use mi-aqara plugin for all another Xiaomi devices.
Thank you again!
