### ISSUE TITLE
Siri控制异常，如果说“关闭空调”，空调反而并开机；在开机时，用Siri命令关闭不了空调。手动控制功能正确

### ISSUE THREAD

**Issue by HelloMorningStar** [LASER-Yi/homebridge-mi-acpartner#58]
@LASER-Yi Siri控制异常，如果在关机时说“嗨Siri！关闭空调”，空调反而会开机；在开机时，用Siri命令关闭不了空调。手动控制所有功能都正确。

 {
			"platform": "XiaoMiAcPartner",
			"devices": {
				"192.168.2.125": "420809f101a4023c0966a86xxxxxxxx0",
				"192.168.2.183": "3b1c60baa2176fecb3706d24xxxxxxxx"
				
			},
			"accessories": [{
					"name": "AC Partner 1",
					"type": "climate",
					"deviceIp": "192.168.2.125",
					"customize": {
					"off": "FE000000000000000000000000070074229B002B0032003B009D0125038E138845131111111211111112131112131313121313131312021111120211111211120211111102131202111211111213131313111311111202111103451311111111120211111311120311111213131313131313131311111112111111120211111301111313021313111112021111120211111313061C",
					"on": "",
					"auto": "FE00000000000000000000000006003A2260002D003B009F0127038E138834020101010101010101020101020202020102020202020202020101010101010101010101020101020201020201010101010101010202020205E3",
					"heat": {
						"30": "FE00000000000000000000000007003A2261002F0038003D009D012B038E1388450301010101010101010301010303030301030303030313030301011101020101010101011103030303010101010203020101010203030303067E",
						"29": "FE00000000000000000000000007003A2261002E00390040009E0128038B13884503010101010101020113010103031303010303030303030303010101010101010111010103010303030101010101030101010101030303030679",
						"28": "FE00000000000000000000000006003A2260002F0038009D012A038B138834020101110101010101020101010101010202020202020202020101010101010101010101010102020201010101010201010101010202020205EC",
						"27": "FE00000000000000000000000006003A2260002F0039009E01220391138834020101010101010101020101020202020102020202020202020101010101010101010101020201020201010101010201010101010202020205E0",
						"26": "FE00000000000000000000000006003A2260002F0039009D0125038E138834020101010101010101020101010101010202020202020202020101010101010101010101010201020201010101010201010101010202020205DB",
						"25": "FE00000000000000000000000007003A2261002F00380040009D012B038B13884503010101010101010103010101110101030303030303030303010101010101010101010103010103030101010101030102011101030303030663",
						"24": "FE00000000000000000000000007003A2261002F00390040009D0128038D13884503010101010101010103010103010101030303030303030303010101010111010101010111010103030101010101030101020101030303030663",
						"23": "FE00000000000000000000000007003A2261002F0038003E009D0127038C13884513010101010101020103010103030303010303030303030303011101010101010101010103030301030101010101030201110201030303030678",
						"22": "FE00000000000000000000000007003A2261002F0037003D009D01270390138845030101010101011101030101110101010313031303130303031101020101010101110201010313010302010202010301010102010303030306C5",
						"21": "FE00000000000000000000000007003A2261002C0032003A009D012503911388451311111112011111111312111211111103131313131313131312021111111211111111111302130213120211111113111111111203131313064E",
						"20": "FE00000000000000000000000006003A2260002F0039009D0128038B138834020101110101010101020101020101010202020202020202020101010101010101010101010102010201010101010201010101010202020205EB",
						"19": "FE00000000000000000000000006003A2260002F0038009D012A038B138834020101010101010101020101010101010202020212020202020101010101010101010101020201110201010101010201010101010202020205FC",
						"18": "FE00000000000000000000000006003A2260002F0038009D0128038B138834020101010101010101020101020101010202020202020202020101010101010101010101010201010201010101010201010101010202020205DA",
						"17": "FE00000000000000000000000007003A2261002F0039003F009D0129038C13884503010101010101010113010103010101030303030303030303010101010101011101020103010101030101010101130201010101030303130683"
						},
					"cool": {
						"30": "FE00000000000000000000000006003A2260002F0038009D0128038B138834020101010101010101020101020202021102020202020202020101010101010101010101010202020201010102011101010101010202020205FE",
						"29": "FE00000000000000000000000006003A2260002F0038009D0128038C138834020101010101010101020101020202020102020202020202020101010101010101010101020102020201010102010101010101010202020205DF",
						"28": "FE00000000000000000000000006003A2260002F0039009D01230391138834020101010101010101020101010101010202020202020202020101010101010101010101010102020201010102010101010101010202020205DC",
						"27": "FE00000000000000000000000006003A2260002F0039009D012A038B138834020101010101010101020101020202020102020202020202020101010101010101010101020201020201010102010101010101010202020205E1",
						"26": "FE00000000000000000000000006003A2260002F0038009D0127038F138834020101010101010101020101010101010202020202020202020101010101010101010101010201020201010102010101010111010202020205ED",
						"25": "FE00000000000000000000000007003A2261002F00380040009C012B038B13884503010101010101010103010101110101030303030303031303010101010101010101110103010103030101010301010101010102030303030672",
						"24": "FE00000000000000000000000007003A2261002F00390040009D012A038C13884503010101010101010203010103010101030303030303030303010101010101010101010101010113030101010301010101010101030303030654",
						"23": "FE00000000000000000000000006003A226000300038009D0128038B138834020101010101010101020101020202020102020202020202020101010101010101010101020202010201010102010101010101010202020205DF",
						"22": "FE00000000000000000000000006003A2260002F0038009D01250391138834020101010101010101020101010101010202020202020202020101010101010101010101010202010201010102010101010101010202020205DD",
						"21": "FE00000000000000000000000006003A2260002F0039009D01220391138834120101010101010101020101010101010202020202020202020101010101010101010101020102010201010102010101010101010202020205EB",
						"20": "FE00000000000000000000000006003A2260002F0038009D012A038E138834020101010101010101020101020101010202020202020202020101010101010101010101010102010201010102010101010101010202020205DF",
						"19": "FE00000000000000000000000007003A2261002F0037003E009D012B038D13884513010101010102010103010102010201030303031303030303010101020101010101010103130201030101010311010101011101030303030696",
						"18": "FE00000000000000000000000007003A2261002F0037003D009D0124039113884503010201010101110103010113011101030303030303030303010101010101010102010101030101030101020301020101010101030303130681",
						"17": "FE00000000000000000000000006003A2260002F0038009D0129038B138834020101010101010101020101020111010202020202020202020101010101010101010101010201010201010102010101010101010202020205EB"
						}					
					},
					"syncInterval": "0",
					"autoStart": "auto",
					"sensorSid": "lumi.158d00015xxxxx"
					}, {
					"name": "AC Partner 2",
					"type": "climate",
					"deviceIp": "192.168.2.183",
					"customize": {
					"off": "FE00000000000000000000000005001E22430034009D01AB034713883201000000010000000101000000000000000000000001000100000001049F",
					"on": "FE00000000000000000000000005001E2243003400A001A8034A1388320100000001000000000000000000000001000001000100000101000104A3",
					"auto": "FE00000000000000000000000005001E2243003400A001A8034A1388320100000001000000000000000000000001000001000100000101000104A3",
					"heat": {
						"30": "FE00000000000000000000000005001E22430034009E01A8034B1388320100000001000000000000000101000001010101000100010000000004A4",
						"29": "FE00000000000000000000000005001E22430034009D01A8034A1388320100000001000000000000000101000001010100000100010101010104A5",
						"28": "FE00000000000000000000000006001E2244002D003C00A501A8034B13884302010101020001010101010102020101020201020102010202020201050F",
						"27": "FE00000000000000000000000006001E2244002E003A00A301A7034A13884302010101020101010101010102020101020201010102010202020102050A",
						"26": "FE00000000000000000000000005001E22430034009D01A8034B1388320100000001000000000000000101000001000101000100010101000004A4",
						"25": "FE00000000000000000000000005001E2243003300A201A7034B1388320100000001000000000000000101000001000100000100010100010104A7",
						"24": "FE00000000000000000000000006001E2244002D003C00A501A8034A13884302010101020101010101010102020101020101020102010202010201050D",
						"23": "FE00000000000000000000000005001E22430034009F01A7034B1388320100000001000000000000000101000001000000000100010100000104A3",
						"22": "FE00000000000000000000000006001E2244002F003A00A301A8034A138843020101010201000100010101020201010102020201020102020101010509",
						"21": "FE00000000000000000000000005001E2243003300A001A7034B1388320100000001000000000000000101000000010100000100010001010104A5",
						"20": "FE00000000000000000000000005001E22430033009F01A7034A1388320100000001000000000000000101000000010001000100010001010004A2",
						"19": "FE00000000000000000000000005001E2243003300A201A7034A1388320100000001000000000000000101000000010000000100010001000104A4",
						"18": "FE00000000000000000000000005001E22430034009D01A7034913883201000000010000000000000001010000000001010001000100010000049F",
						"17": "FE00000000000000000000000005001E2243003300A101A7034A1388320100000001000000000000000101000000000100000100010000010104A3"
						},
					"cool": {
						"30": "FE00000000000000000000000006001E2244002D003C00A501A7034B13884302010101020101010101010102010101020202020102010202020101050E",
						"29": "FE00000000000000000000000005001E22430034009D01A8034A1388320100000001000000000000000100000001010100000100010100010104A3",
						"28": "FE00000000000000000000000005001E22430034009D01A7034A1388320100000001000000000000000100000001010001000100010100010004A1",
						"27": "FE00000000000000000000000006001E2244002E003B00A301A70349138843020101010201010101010101020101010202010101020102020101020508",
						"26": "FE00000000000000000000000005001E22430034009D01A803491388320100000001000000000000000100000001000101000100010100000004A0",
						"25": "FE00000000000000000000000005001E22430034009D01A7034A1388320100000001000000000000000100000001000100000100010001010104A1",
						"24": "FE00000000000000000000000005001E22430034009D01AB03471388320100000001000000000000000100000001000001000100010001010004A1",
						"23": "FE00000000000000000000000005001E2243003300A001A7034B1388320100000001000000000000000100000001000000000100010001000104A2",
						"22": "FE00000000000000000000000005001E2243003300A001A703491388320100000001000000000000000100000000010101000100010001000004A1",
						"21": "FE00000000000000000000000006001E22440031003A00A201A703491388430200000002000000000101000201010100020200010201020001020205FE",
						"20": "FE00000000000000000000000006001E2244002E003A00A401A8034B13884302010101020101010101010102010101010201020102010201010201050A",
						"19": "FE00000000000000000000000006001E22440033003A00A001A8034A138843020000001200000000000000020000000002000000020002000000020504",
						"18": "FE00000000000000000000000005001E22430034009E01A8034A1388320100000001000000000000000100000000000101000100010000000004A0",
						"17": "FE00000000000000000000000005001E22430034009E01A8034A1388320100000001000000000000000100000000000101000100010000000004A0"
						}					
					},
					"syncInterval": "0",
					"autoStart": "heat",
					"sensorSid": "lumi.158d00015xxxxx"
					}
			]}

**Comment by HelloMorningStar** [comment]
AC Partner 1是小米空调伴侣，AC Partner 2是Aqara空调伴侣。

**Comment by HelloMorningStar** [comment]
怎样获得空调码？ 文档说“大部分空调码以01开头”

**Comment by LASER-Yi** [comment]
获取空调码的方式请参考[Wiki](https://github.com/LASER-Yi/homebridge-mi-acpartner/wiki/Use-Wireshark-to-get-AC-code-or-IR-code-of-you-AC%5BCN%5D)页面

Siri控制很多人也反应过这个问题，但是好像是苹果那边对于控制这块的定义不同，所以目前暂时无法解决

**Comment by Lon1st** [comment]
感觉是中文Siri的bug，切换成英语说shut down就没问题。
