### ISSUE TITLE
修改为platform后伴侣下其他子配件是否在Homekit下可控

### ISSUE THREAD

**Issue by jerry-qin** [LASER-Yi/homebridge-mi-acpartner#7]
还没有买小米空调伴侣，但因为这代空调伴侣没后开发局域网协议，早些时候无法接入Homekit,现在逛到这边发现已经能接入了，所有咨询下这里大神，目前接入后空调伴侣下挂着的其他子配件能否能被Homekit识别出来并且正常使用？特别是0.4.0修改为platform后感觉有戏。如果可以，就去买一个空调伴侣玩玩

**Comment by LASER-Yi** [comment]
目前版本的空调伴侣因为不支持局域网通信协议，所以还无法识别出挂着的其他子配件，可以等待空调伴侣升级。修改为platform只是因为需要支持红外开关。

在 2017年10月22日 上午7:55，敲冰块 <notifications@github.com>写道：

**Comment by jerry-qin** [comment]
OK,多谢
