### ISSUE TITLE
iOS和Mac如何获取温湿度传感器的设备码

### ISSUE THREAD

**Issue by HarryChen55** [LASER-Yi/homebridge-mi-acpartner#8]
你好，请问ios和Mac下如何获取温湿度传感器的设备码？
我没有安卓的设备，没办法通过安卓的app获取。
谢谢！

**Comment by LASER-Yi** [comment]
mac下可以安装安卓模拟器获取，或者绑定到网关 获取到设备码以后再绑定回空调伴侣

发自我的 iPhone
