### ISSUE TITLE
Inappropriate OOP practice

### ISSUE THREAD

**Issue by Willian-Zhang** [LASER-Yi/homebridge-mi-acpartner#86]
https://github.com/LASER-Yi/homebridge-mi-acpartner/blob/23425c8ea2cb541c3bebfc51476c80d8a9b70105/accessories/base.js#L2-L27

Parsing a config file while constructing your Hardware Abstraction isn't really a good best practice for Class Abstraction in OOP.
Config file, can be viewed as a set of static State, is not recommended to be mixed or shuffled and encapsulated in a class with other state representations (`BaseAccessories` class in this case).

**Comment by Willian-Zhang** [comment]
see #85 for a bug-fix of which might indirectly caused by this and not intuitive as for debugging

**Comment by LASER-Yi** [comment]
Thx for your suggestion, request is merged.
